"""Unit tests for the Ollama client module."""

import json
from unittest.mock import MagicMock, patch

import pytest

from docsummarizer.ollama_client import (
    get_ollama_host,
    get_ollama_model,
    is_ollama_available,
    query_ollama,
)


def test_ollama_default_host_and_model(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("OLLAMA_HOST", raising=False)
    monkeypatch.delenv("OLLAMA_MODEL", raising=False)
    assert get_ollama_host() == "http://localhost:11434"
    assert get_ollama_model() == "llama3"


def test_ollama_custom_host_and_model(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("OLLAMA_HOST", "http://192.168.1.50:11434/")
    monkeypatch.setenv("OLLAMA_MODEL", "mistral")
    assert get_ollama_host() == "http://192.168.1.50:11434"
    assert get_ollama_model() == "mistral"


@patch("urllib.request.urlopen")
def test_is_ollama_available_success(mock_urlopen: MagicMock) -> None:
    mock_resp = MagicMock()
    mock_resp.status = 200
    mock_urlopen.return_value.__enter__.return_value = mock_resp

    assert is_ollama_available() is True


@patch("urllib.request.urlopen")
def test_is_ollama_available_failure(mock_urlopen: MagicMock) -> None:
    mock_urlopen.side_effect = Exception("Connection refused")

    assert is_ollama_available() is False


@patch("urllib.request.urlopen")
def test_query_ollama_success(mock_urlopen: MagicMock) -> None:
    mock_resp = MagicMock()
    response_data = json.dumps({"response": "Summary generated by Ollama"}).encode("utf-8")
    mock_resp.read.return_value = response_data
    mock_urlopen.return_value.__enter__.return_value = mock_resp

    res = query_ollama(
        prompt="Summarize this text",
        system_prompt="You are helpful",
        model="llama3",
        json_mode=True,
    )
    assert res == "Summary generated by Ollama"


@patch("urllib.request.urlopen")
def test_query_ollama_error(mock_urlopen: MagicMock) -> None:
    mock_urlopen.side_effect = Exception("HTTP 500 Error")
    with pytest.raises(Exception, match="HTTP 500 Error"):
        query_ollama("Test prompt")
